Update main.yml
Signed-off-by: AlenaA <299809679+alenaz198383@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -219,68 +219,55 @@ jobs:
           echo "$SENTRY_CLI_OPTIONS" > Assets/Plugins/Sentry/SentryCliOptions.asset
           androidVersionCode=$(cat ProjectSettings/androidVersionCode.txt | tr -d '[:space:]')
           buildVersion=$(cat ProjectSettings/buildVersion.txt | tr -d '[:space:]')
-          echo "ANDROID_VERSION_CODE=$androidVersionCode" >> $GITHUB_ENV
-          echo "VERSION=$buildVersion" >> $GITHUB_ENV
           echo "Detected version: $buildVersion, code: $androidVersionCode"
+          #
+          DEST="ProjectSettings/ProjectSettings.asset"
+          cp "$DEST" "$DEST.bak"
+          #
+          sed -i "s/^  bundleVersion: .*/  bundleVersion: $buildVersion/" "$DEST"
+          sed -i "s/^  AndroidBundleVersionCode: .*/  AndroidBundleVersionCode: $androidVersionCode/" "$DEST"
 
-      #- name: Extract Build Versions (File or Input)
-      #  run: |
-      #    CUSTOM_VER="${{ inputs.custom_build_version }}"
-      #    #
-      #    # --- Логика для VERSION (buildVersion.txt) ---
-      #    if [ -n "$CUSTOM_VER" ]; then
-      #      echo "Using custom build version from input: $CUSTOM_VER"
-      #      BUILD_VERSION="$CUSTOM_VER"
-      #      #
-      #      # 2. Валидация формата X.Y.Z (три числа через точку)
-      #      # Регулярка проверяет: начало строки, число, точка, число, точка, число, конец строки
-      #      if ! [[ "$BUILD_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-      #        echo "Error: Invalid version format '$BUILD_VERSION'. Expected format is X.Y.Z (e.g., 1.2.3)" >&2
-      #        exit 1
-      #      fi
-      #      #
-      #      # 3. Парсим X, Y, Z
-      #      # Используем IFS (Internal Field Separator) для разбиения строки по точке
-      #      IFS='.' read -r X Y Z <<< "$BUILD_VERSION"
-      #      #
-      #      # На всякий случай проверяем, что переменные не пустые (защита от странных багов)
-      #      if [ -z "$X" ] || [ -z "$Y" ] || [ -z "$Z" ]; then
-      #        echo "Error: Failed to parse version components from '$BUILD_VERSION'" >&2
-      #        echo "major: $X"
-      #        echo "minor: $Y"
-      #        echo "patch: $Z"
-      #        exit 1
-      #      fi
-      #      #
-      #      # 4. Вычисляем ANDROID_VERSION_CODE
-      #      ANDROID_CODE=$((X * 1000000 + Y * 1000 + Z))
-      #      #
-      #      echo "Parsed components: X=$X, Y=$Y, Z=$Z"
-      #      echo "Calculated ANDROID_VERSION_CODE: $ANDROID_CODE"
-      #    else
-      #      # Если инпут пустой, читаем из файла
-      #      if [ ! -f "ProjectSettings/buildVersion.txt" ]; then
-      #        echo "Error: ProjectSettings/buildVersion.txt not found and no custom version provided." >&2
-      #        exit 1
-      #      fi
-      #      if [ ! -f "ProjectSettings/androidVersionCode.txt" ]; then
-      #        echo "Error: ProjectSettings/androidVersionCode.txt not found and no custom code provided." >&2
-      #        exit 1
-      #      fi
-      #      ANDROID_CODE=$(cat ProjectSettings/androidVersionCode.txt | tr -d '[:space:]')
-      #      BUILD_VERSION=$(cat ProjectSettings/buildVersion.txt | tr -d '[:space:]')
-      #      echo "Using android version code from file: $ANDROID_CODE"
-      #      echo "Using build version from file: $BUILD_VERSION"
-      #    fi
-      #    #
-      #    # Экспортируем переменные в окружение для следующих шагов
-      #    echo "CUSTOM_VERSION=$BUILD_VERSION" >> "$GITHUB_ENV"
-      #    echo "CUSTOM_ANDROID_VERSION_CODE=$ANDROID_CODE" >> "$GITHUB_ENV"
-      #
-      #- name: Show Versions (тестируем)
-      #  run: |
-      #    echo "Test CUSTOM_VERSION: ${{ env.CUSTOM_VERSION }}"
-      #    echo "Test CUSTOM_ANDROID_VERSION_CODE: ${{ env.CUSTOM_ANDROID_VERSION_CODE }}"
+      - name: Extract Build Versions (File or Input)
+        run: |
+          CUSTOM_VER="${{ inputs.custom_build_version }}"
+          #
+          # --- Логика для VERSION (buildVersion.txt) ---
+          if [ -n "$CUSTOM_VER" ]; then
+            echo "Using custom build version from input: $CUSTOM_VER"
+            BUILD_VERSION="$CUSTOM_VER"
+            #
+            # 2. Валидация формата X.Y.Z (три числа через точку)
+            # Регулярка проверяет: начало строки, число, точка, число, точка, число, конец строки
+            if ! [[ "$BUILD_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Error: Invalid version format '$BUILD_VERSION'. Expected format is X.Y.Z (e.g., 1.2.3)" >&2
+              exit 1
+            fi
+            #
+            # 3. Парсим X, Y, Z
+            # Используем IFS (Internal Field Separator) для разбиения строки по точке
+            IFS='.' read -r X Y Z <<< "$BUILD_VERSION"
+            #
+            # На всякий случай проверяем, что переменные не пустые (защита от странных багов)
+            if [ -z "$X" ] || [ -z "$Y" ] || [ -z "$Z" ]; then
+              echo "Error: Failed to parse version components from '$BUILD_VERSION'" >&2
+              echo "major: $X"
+              echo "minor: $Y"
+              echo "patch: $Z"
+              exit 1
+            fi
+            #
+            # 4. Вычисляем ANDROID_VERSION_CODE
+            ANDROID_CODE=$((X * 1000000 + Y * 1000 + Z))
+            #
+            echo "Parsed components: X=$X, Y=$Y, Z=$Z"
+            echo "Calculated ANDROID_VERSION_CODE: $ANDROID_CODE"
+          else
+            BUILD_VERSION=$(grep -oP 'bundleVersion:\s*\K[\d.]+' ProjectSettings/ProjectSettings.asset)
+            ANDROID_CODE=$(grep -oP 'AndroidBundleVersionCode:\s*\K\d+' ProjectSettings/ProjectSettings.asset)
+          fi
+          #
+          echo "VERSION=$BUILD_VERSION" >> "$GITHUB_ENV"
+          echo "ANDROID_VERSION_CODE=$ANDROID_CODE" >> "$GITHUB_ENV"
 
       - name: Show Final Using Versions
         run: |
@@ -363,6 +350,22 @@ jobs:
           date -u
           df -h
           free -h || true
+
+      - name: Revert `ProjectSettings/ProjectSettings.asset`
+        continue-on-error: true
+        if: steps.buildStep.outcome == 'success'
+        run: |
+          DEST="ProjectSettings/ProjectSettings.asset"
+          chmod +x .github/scripts/helpers.sh && source .github/scripts/helpers.sh
+          check_file "$DEST"
+          check_file "$DEST.bak"
+          #
+          rm "$DEST"
+          check_file "$DEST"
+          #
+          mv "$DEST.bak" "$DEST"
+          check_file "$DEST"
+          check_file "$DEST.bak"
 
       #- name: Upload Build as GitHub artifact
       #  uses: actions/upload-artifact@v7
