Update main.yml
Signed-off-by: AlenaA <299809679+alenaz198383@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,11 @@ on:
       - published
   workflow_dispatch:
     inputs:
+      custom_build_version:
+        description: 'Версия сборки (формат 1.2.3). Оставьте пустым, чтобы взять из buildVersion.txt'
+        required: false
+        type: string
+        default: ''
       # Main job
       run_tests:
         description: 'Run Tests'
@@ -189,6 +194,41 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Extract Build Versions (File or Input)
+        run: |
+          CUSTOM_VER="${{ inputs.custom_build_version }}"
+          #
+          # --- Логика для VERSION (buildVersion.txt) ---
+          if [ -n "$CUSTOM_VER" ]; then
+            echo "Using custom build version from input: $CUSTOM_VER"
+            BUILD_VERSION="$CUSTOM_VER"
+            #echo "Using custom android version code from input: $CUSTOM_CODE"
+            #ANDROID_CODE="$CUSTOM_CODE"
+          else
+            # Если инпут пустой, читаем из файла
+            if [ ! -f "ProjectSettings/buildVersion.txt" ]; then
+              echo "Error: ProjectSettings/buildVersion.txt not found and no custom version provided." >&2
+              exit 1
+            fi
+            if [ ! -f "ProjectSettings/androidVersionCode.txt" ]; then
+              echo "Error: ProjectSettings/androidVersionCode.txt not found and no custom code provided." >&2
+              exit 1
+            fi
+            ANDROID_CODE=$(cat ProjectSettings/androidVersionCode.txt | tr -d '[:space:]')
+            echo "Using android version code from file: $ANDROID_CODE"
+            BUILD_VERSION=$(cat ProjectSettings/buildVersion.txt | tr -d '[:space:]')
+            echo "Using build version from file: $BUILD_VERSION"
+          fi
+          #
+          # Экспортируем переменные в окружение для следующих шагов
+          echo "CUSTOM_VERSION=$BUILD_VERSION" >> "$GITHUB_ENV"
+          echo "CUSTOM_ANDROID_VERSION_CODE=$ANDROID_CODE" >> "$GITHUB_ENV"
+
+      - name: Show Detected Versions
+        run: |
+          echo "Final VERSION: ${{ env.CUSTOM_VERSION }}"
+          echo "Final ANDROID_VERSION_CODE: ${{ env.CUSTOM_ANDROID_VERSION_CODE }}"
+
       - name: Restore cache from R2
         id: restore_cache_r2
         env:
@@ -304,6 +344,7 @@ jobs:
       #    retention-days: 1
 
       - name: Upload Build to R2
+        continue-on-error: true
         if: steps.buildStep.outcome != 'skipped'
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
