Update main.yml
Signed-off-by: AlenaA <299809679+alenaz198383@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -453,10 +453,50 @@ jobs:
           #
           #rm -rf artifacts/
 
-      #- name: 📈 Upload AAB to Sentry for Size Tracking
-      #  timeout-minutes: 2
+      - name: 📈 Upload AAB to Sentry for Size Tracking
+        timeout-minutes: 2
+        continue-on-error: true
+        if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab' && github.event_name == 'workflow_dispatch' && inputs.sentry_size_analysis_enabled
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
+          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
+        run: |
+          AAB_FILE=$(find build -name "*.aab" | head -n 1)
+          if [ -n "$AAB_FILE" ]; then
+            echo "All '*.aab' files found:"
+            find build -name "*.aab"
+            echo "Using: $AAB_FILE"
+            RELEASE_NAME="game2048@${{ env.VERSION }}"
+            #
+            echo ""; echo "----- Creating Sentry release ($RELEASE_NAME) executed... -----"
+            time sentry-cli releases new "$RELEASE_NAME" \
+              --org "$SENTRY_ORG" \
+              --project "$SENTRY_PROJECT" \
+              --finalize \
+              ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
+            echo "----- Creating Sentry release ($RELEASE_NAME) completed -----"; echo ""
+            #
+            #echo ""; echo "----- Uploading AAB to Sentry executed... -----"
+            #time sentry-cli build upload "$AAB_FILE" \
+            #  --org "$SENTRY_ORG" \
+            #  --project "$SENTRY_PROJECT" \
+            #  --build-configuration Release \
+            #  --head-sha "${{ github.sha }}" \
+            #  --head-repo-name "gal20040/2048" \
+            #  --vcs-provider github \
+            #  --force-git-metadata \
+            #  ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
+            #echo "----- Uploading AAB to Sentry completed -----"; echo ""
+          else
+            echo "AAB file not found."
+            exit 1
+          fi
+
+      #- name: 📈 Upload '*mapping*' to Sentry
+      #  timeout-minutes: 1
       #  continue-on-error: true
-      #  if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab' && github.event_name == 'workflow_dispatch' && inputs.sentry_size_analysis_enabled
+      #  if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab'
       #  env:
       #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
       #    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
@@ -464,112 +504,72 @@ jobs:
       #  run: |
       #    AAB_FILE=$(find build -name "*.aab" | head -n 1)
       #    if [ -n "$AAB_FILE" ]; then
-      #      echo "All '*.aab' files found:"
-      #      find build -name "*.aab"
-      #      echo "Using: $AAB_FILE"
-      #      RELEASE_NAME="game2048@${{ env.VERSION }}"
-      #      #
-      #      echo ""; echo "----- Creating Sentry release ($RELEASE_NAME) executed... -----"
-      #      time sentry-cli releases new "$RELEASE_NAME" \
-      #        --org "$SENTRY_ORG" \
-      #        --project "$SENTRY_PROJECT" \
-      #        --finalize \
-      #        ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
-      #      echo "----- Creating Sentry release ($RELEASE_NAME) completed -----"; echo ""
-      #      #
-      #      #echo ""; echo "----- Uploading AAB to Sentry executed... -----"
-      #      #time sentry-cli build upload "$AAB_FILE" \
-      #      #  --org "$SENTRY_ORG" \
-      #      #  --project "$SENTRY_PROJECT" \
-      #      #  --build-configuration Release \
-      #      #  --head-sha "${{ github.sha }}" \
-      #      #  --head-repo-name "gal20040/2048" \
-      #      #  --vcs-provider github \
-      #      #  --force-git-metadata \
-      #      #  ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
-      #      #echo "----- Uploading AAB to Sentry completed -----"; echo ""
+      #      echo "All '*mapping*' files found:"
+      #      find build -name "*mapping*"
+      #      # Upload R8/ProGuard mapping if it exists
+      #      MAPPING_FILE=$(find build -name "*mapping*" | head -n 1)
+      #      if [ -n "$MAPPING_FILE" ]; then
+      #        echo ""; echo "----- Uploading mapping to Sentry executed... -----"
+      #        time find build -name "*mapping*" | xargs sentry-cli upload-proguard \
+      #          --org "$SENTRY_ORG" \
+      #          --project "$SENTRY_PROJECT" \
+      #          ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
+      #        echo "----- Uploading mapping to Sentry completed -----"; echo ""
+      #      else
+      #        echo "No '*mapping*' found (minification may be disabled)"
+      #      fi
       #    else
       #      echo "AAB file not found."
       #      exit 1
       #    fi
-
-      - name: 📈 Upload '*mapping*' to Sentry
-        timeout-minutes: 1
-        continue-on-error: true
-        if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab'
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
-          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
-        run: |
-          AAB_FILE=$(find build -name "*.aab" | head -n 1)
-          if [ -n "$AAB_FILE" ]; then
-            echo "All '*mapping*' files found:"
-            find build -name "*mapping*"
-            # Upload R8/ProGuard mapping if it exists
-            MAPPING_FILE=$(find build -name "*mapping*" | head -n 1)
-            if [ -n "$MAPPING_FILE" ]; then
-              echo ""; echo "----- Uploading mapping to Sentry executed... -----"
-              time find build -name "*mapping*" | xargs sentry-cli upload-proguard \
-                --org "$SENTRY_ORG" \
-                --project "$SENTRY_PROJECT" \
-                ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
-              echo "----- Uploading mapping to Sentry completed -----"; echo ""
-            else
-              echo "No '*mapping*' found (minification may be disabled)"
-            fi
-          else
-            echo "AAB file not found."
-            exit 1
-          fi
-
-      - name: 📈 Upload symbol's files to Sentry
-        timeout-minutes: 1
-        continue-on-error: true
-        if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab'
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
-          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
-        run: |
-          AAB_FILE=$(find build -name "*.aab" | head -n 1)
-          if [ -n "$AAB_FILE" ]; then
-            echo ""; echo "----- Uploading symbol's files to Sentry executed... -----"
-            time sentry-cli debug-files upload \
-              --org "$SENTRY_ORG" \
-              --project "$SENTRY_PROJECT" \
-              --il2cpp-mapping \
-              build/ \
-              ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
-            echo "----- Uploading symbol's files to Sentry completed -----"; echo ""
-          else
-            echo "AAB file not found."
-            exit 1
-          fi
-
-      - name: 📈 Upload symbol's files to Sentry
-        timeout-minutes: 2
-        continue-on-error: true
-        if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab'
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
-          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
-        run: |
-          AAB_FILE=$(find build -name "*.aab" | head -n 1)
-          if [ -n "$AAB_FILE" ]; then
-            echo ""; echo "----- Uploading symbol's files to Sentry executed... -----"
-            time sentry-cli debug-files upload \
-              --org "$SENTRY_ORG" \
-              --project "$SENTRY_PROJECT" \
-              --il2cpp-mapping \
-              ./ \
-              ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
-            echo "----- Uploading symbol's files to Sentry completed -----"; echo ""
-          else
-            echo "AAB file not found."
-            exit 1
-          fi
+      #
+      #- name: 📈 Upload symbol's files to Sentry
+      #  timeout-minutes: 1
+      #  continue-on-error: true
+      #  if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab'
+      #  env:
+      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+      #    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
+      #    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
+      #  run: |
+      #    AAB_FILE=$(find build -name "*.aab" | head -n 1)
+      #    if [ -n "$AAB_FILE" ]; then
+      #      echo ""; echo "----- Uploading symbol's files to Sentry executed... -----"
+      #      time sentry-cli debug-files upload \
+      #        --org "$SENTRY_ORG" \
+      #        --project "$SENTRY_PROJECT" \
+      #        --il2cpp-mapping \
+      #        build/ \
+      #        ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
+      #      echo "----- Uploading symbol's files to Sentry completed -----"; echo ""
+      #    else
+      #      echo "AAB file not found."
+      #      exit 1
+      #    fi
+      #
+      #- name: 📈 Upload symbol's files to Sentry
+      #  timeout-minutes: 2
+      #  continue-on-error: true
+      #  if: steps.buildStep.outcome == 'success' && matrix.exportMode == 'aab'
+      #  env:
+      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+      #    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
+      #    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
+      #  run: |
+      #    AAB_FILE=$(find build -name "*.aab" | head -n 1)
+      #    if [ -n "$AAB_FILE" ]; then
+      #      echo ""; echo "----- Uploading symbol's files to Sentry executed... -----"
+      #      time sentry-cli debug-files upload \
+      #        --org "$SENTRY_ORG" \
+      #        --project "$SENTRY_PROJECT" \
+      #        --il2cpp-mapping \
+      #        ./ \
+      #        ${{ inputs.sentry_debug == true && '--log-level debug' || '' }}
+      #      echo "----- Uploading symbol's files to Sentry completed -----"; echo ""
+      #    else
+      #      echo "AAB file not found."
+      #      exit 1
+      #    fi
 
       - name: Post android build info
         timeout-minutes: 1
