Update main.yml
Signed-off-by: AlenaA <299809679+alenaz198383@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,6 +54,10 @@ on:
           - rustore
           - choose_one
         default: choose_one
+      isProduction:
+        description: 'isProduction'
+        type: boolean
+        default: false
       sentry_size_analysis_enabled:
         description: 'Enable AAB_s Size Analysis in Sentry'
         type: boolean
@@ -67,10 +71,6 @@ on:
         required: false
         type: string
         default: ''
-      isProduction:
-        description: 'isProduction'
-        type: boolean
-        default: false
 
 jobs:
   check_secrets:
@@ -1008,6 +1008,36 @@ jobs:
           find $DIR -type f \( -iname "*r8.json*" \) | zip $archive_name -@
           #
           time aws s3 cp "$archive_name" "s3://$R2_BUCKET/${{ env.ANDROID_VERSION_CODE }}/$archive_name" --endpoint-url $R2_ENDPOINT --quiet
+
+      - name: 🗜️ Find and upload proguard for ads-mobile-sdk
+        continue-on-error: true
+        timeout-minutes: 5
+        if: always() && steps.run_R8_configuration_analyzer.outcome != 'skipped'
+        #env:
+        #  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
+        #  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
+        #  AWS_DEFAULT_REGION: us-east-1
+        #  R2_BUCKET: ${{ secrets.R2_BUCKET_NAME }}
+        #  R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
+        run: |
+          DIR="${{ github.workspace }}"
+          #
+          if [ ! -d "$DIR" ]; then
+            echo "'$DIR' folder not found, skipping uploading it to R2."
+            exit 1
+          fi
+          #
+          source .github/scripts/helpers.sh
+          #
+          echo "=== '*proguard.txt*' files in '$DIR' ==="
+          find $DIR -type f \( -iname "*proguard.txt*" \) 2>/dev/null
+          # .gradle/caches/9.5.1/transforms/fab4be94b19d7651db176131e5944978/transformed/jetified-ads-mobile-sdk-1.4.0/proguard.txt
+          echo "================================="
+          ##
+          #archive_name="r8.json_in_gh_ws.zip"
+          #find $DIR -type f \( -iname "*r8.json*" \) | zip $archive_name -@
+          ##
+          #time aws s3 cp "$archive_name" "s3://$R2_BUCKET/${{ env.ANDROID_VERSION_CODE }}/$archive_name" --endpoint-url $R2_ENDPOINT --quiet
 
       - name: Final timestamp
         continue-on-error: true
